trigger:
- main

variables:
- template: project.yml

jobs:
- job: ReadVariables
  pool:
    vmImage: ubuntu-latest

  steps:
  - script: |
      echo "Value of myVariable: $(myVariable)"
      echo "Value of anotherVar: $(anotherVar)"
    displayName: Read variables from project.yml
